// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBook = "books"

// Book mapped from table <books>
type Book struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title        string    `gorm:"column:title" json:"title"`
	Year         int32     `gorm:"column:year" json:"year"`
	Prize        float32   `gorm:"column:prize" json:"prize"`
	Genre        string    `gorm:"column:genre" json:"genre"`
	Isbn         string    `gorm:"column:isbn" json:"isbn"`
	CreatedAt    time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	AuthorID     int32     `gorm:"column:author_id" json:"author_id"`
	Availability int32     `gorm:"column:Availability" json:"Availability"`
}

// TableName Book's table name
func (*Book) TableName() string {
	return TableNameBook
}
