// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBorrowingRecord = "borrowing_records"

// BorrowingRecord mapped from table <borrowing_records>
type BorrowingRecord struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BooksID    int64     `gorm:"column:books_id" json:"books_id"`
	UsersID    int64     `gorm:"column:users_id" json:"users_id"`
	CreatedAt  time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	ReturnedAt string    `gorm:"column:returned_at" json:"returned_at"`
}

// TableName BorrowingRecord's table name
func (*BorrowingRecord) TableName() string {
	return TableNameBorrowingRecord
}
